Parameters:
  Tag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number
    Default: 0

  TargetGroup:
    Type: String

  Cluster:
    Type: String

  Repository:
    Type: String

  ECSServiceRole:
    Type: String


Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: DuckHunt
          ContainerPort: 8088
          TargetGroupArn: !Ref TargetGroup

  PaperBoyLogs:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "${Cluster}"
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-DuckHunt
      ContainerDefinitions:
        - Name: DuckHunt
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Memory: 128
          LogConfiguration :
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref PaperBoyLogs
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "paperboy-processor"
          MountPoints:
            - SourceVolume: my-vol
              ContainerPath: /var/www/my-vol
          PortMappings:
            - ContainerPort: 8088
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: AWS_RENTAL_SQS_QUEUE
              Value: "https://sqs.us-west-2.amazonaws.com/930038209161/Asteroids-module-modernizeourrentalreturnqueueprocessor"
            - Name: UNICORN_RENTAL_RETURN_ENDPOINT
              Value: "https://skygh32ukf.execute-api.us-west-2.amazonaws.com/v1"
            - Name: REDIS_URL
              Value: "redis://unicorn-rentals.tpgrek.0001.usw2.cache.amazonaws.com:6379"
            - Name: AWS_DEFAULT_REGION
              Value: "us-west-2"
      Volumes:
        - Name: my-vol